### ISSUE TITLE
Theme not found in Appearance Pref after restart (Intellij 14 CE)

### ISSUE THREAD

**Issue by dreyco676** [y3sh/Intellij-Colors-Sublime-Monokai#12] opened 2015-01-24 05:50 UTC
I follow the following instructions:

Download or build the jar (buildJar.sh)
Intellij -> File -> Import Settings -> Select Jar

Intellij then says it will need to restart. I restart it and attempt to select Sublime Monokai as the theme in Settings -> Editor -> Colors & Fonts but it is not an option.

Tried using both the .jar file and building my own with Java 8 update 31 on OSX Yosemite.

**Comment by y3sh** [comment] 2015-01-24 16:58
I just tested it with a fresh install of Intellij CE and it works. Have you tried a clean reinstall?  http://stackoverflow.com/questions/2774315/in-intellij-on-os-x-how-do-you-clear-out-all-global-setting-info-licensing-etc

![test](https://cloud.githubusercontent.com/assets/1032983/5888114/c25c8542-a3b7-11e4-91af-f67a45843c52.png)

**Comment by y3sh** [comment] 2015-01-24 17:00
Closing as cannot reproduce.

**Closed by y3sh** 2015-01-24 17:00 UTC

**Comment by dreyco676** [comment] 2015-01-24 18:25
Thanks, it was a user error. I was looking for the theme under appearance and didn't follow instructions closely enough.

**Comment by EntilZha** [comment] 2015-04-29 21:56
Commenting for future users, sometimes you may have to restart your editor twice (I have run into the same thing for other custom themes) and/or switch to a different theme.
